application: bookbookpresentation
version: 1
runtime: python
api_version: 1

handlers:
  
- url: /css
  static_dir: css
  
- url: /javascripts
  static_dir: javascripts
  
- url: /.*
  script: main.py
